### PR TITLE
Add --pre-data and --post-data to solve integrity checks

### PR DESCRIPTION
**Pull request by arshsingh**

### CODE REVIEW

**Comment by kulte** [comment]
👍 to this functionally. In it's current state, it's usefulness is certainly undermined by lack of a great way to handle foreign keys.

**Comment by kulte** [comment]
How would one handle constraints without this, if there is a good way, out of curiosity? Manually issue the commands in `--pre-data` and `--post-data`?

**Comment by arshsingh** [comment]
Yes, I guess you could copy the schema manually with those two commands  and use pgsync just for data.

I'm currently just installing the lib from the fork: https://github.com/arshsingh/pgsync

**Comment by ankane** [comment]
Hey @arshsingh, thanks for the PR! The naming is a bit unclear. How about something like:

```ruby
pgsync --schema-only --no-constraints
pgsync table1,table2 --add-constraints
```

**Comment by arshsingh** [comment]
Hey @ankane, IMHO `--pre-data` and `--post-data` are better since those are the names used by pg_dump, so it's self-explanatory what these flags will do behind the scenes

About this:
```
pgsync table1,table2 --add-constraints
```
I'm not sure if you can selectively dump the post-data section, since integrity checks span over multiple tables. I will check the docs to confirm,

Let me know what you think, If you feel `--no-constraints` and `--add-constrinats` is better, I'll change these.

**Comment by kulte** [comment]
@ankane is there any plan for merging this. I think the gem would be far more useful with it. @arshsingh WDYT about deferring to @ankane's naming suggestions in the name of getting this merged in. IMO so long as the commands are documented in the README it probably is good, right?

**Comment by jacob-on-github** [comment]
@ankane +1 for merging this; I use @arshsingh's fork

**Comment by arshsingh** [comment]
Thanks @chris72205 I'll fix it

**Comment by ankane** [comment]
Hey @arshsingh, thanks again for the PR, and sorry progress stalled. If you're still using it, can you explain more about how subsequent syncs work? It seems like constraints would get in the way with those as well.

**Comment by arshsingh** [comment]
Hi @ankane. I do a fresh sync every time. I have a script that uses pgsync like this:
- create temp db on destination (e.g.: `create database db_throwaway`)
- run pgsync to sync to this db.
- swap db_throwaway with db on the destination host

(I'll try to update this PR over the weekend)

**Comment by austinh** [comment]
Any update on this? would love this feature!

Thanks

**Comment by ankane** [comment]
Moving the discussion of foreign keys to #59, and hoping to find a way that doesn't require a full schema sync. If you have ideas, please comment over there. Thanks for all the discussion so far.

**Pull request closed without merging**
