### PR TITLE
Enable search_path in connection

### PR DESCRIPTION
**Pull request by lazebny**
### Overview ###
Related to schema tables can be synced if we pass schema in db connection string.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @lazebny, thanks for the PR. I don't think pgsync should modify the search path.

**Comment by lazebny** [comment]
@ankane, thank you for response. Your tool is great and useful in our project (sync data from prod to dev environment).

Need to copy data from one scheme to another, tables are existed only in specific schema but not in public. Test is failed if we use that params string, output say that table not found.

Could you correct me if I use your tool wrong or suggest other way resolving this issue? 

It works well if we set a search path but we don't use a PgBouncer.

Might we can return search_path to origin  in ensure block and make PgBouncer happy?

**Comment by ankane** [comment]
@lazebny Currently, there's no way to sync from one schema to another. PgBouncer only guarantees you get the same connection on a transaction level (in transaction mode), so an ensure block won't help. Is there a reason you can't set `search_path` on the user directly?

**Comment by ankane** [comment]
Cleaning up issues

**Pull request closed without merging**
