### PR TITLE
Add docker configuration for gem development

### PR DESCRIPTION
**Pull request by joxxoxo**
Also adding `PGSYNC_SAFE_DESTINATIONS` env variable to make docker usage
simple and safe

### CODE REVIEW

**Comment by ankane** [comment]
Hey @joxxoxo, thanks for another PR. However, Docker development isn't something I'd like to support.

**Comment by joxxoxo** [comment]
Thanks for the reply. I guess you are referring to `Dockerfile.dev` and `docker-compose.yml` used for the gem development.
What do you think about the other two changes:
1. Adding `postgresql-client` for `Dockerfile` to have `pg_dump`/`pg_restore` working and `git` to track heroku projects
2. Adding `PGSYNC_SAFE_DESTINATIONS` env variable to make gem usage in dockerized environments safer (to use instead of `to_safe` switch)

**Comment by ankane** [comment]
1. I think `postgresql-client` makes sense to include. Can you explain `git` more?
2. I've considered a list of safe hosts in the past, but it's not something I'd like to support right now.

**Comment by joxxoxo** [comment]
1. `git` is used in [heroku detection](https://github.com/ankane/pgsync/blob/90cd26e4363a337111a7956a2f67eb8d149072d8/lib/pgsync/init.rb#L69). Not a critical thing but it's easy to support
2. I think it's quite important for nowadays Dockerized setups, at least in my experience it usually not `localhost` where I have my local DB running. And without safe hosts I need to be really careful not to break staging/production

**Comment by ankane** [comment]
For 1, I don't think Heroku detection is needed since the container won't have access to the Heroku CLI. For 2, still have the same thought as above.

**Comment by ankane** [comment]
Added `postgresql-client` and pushed a new image to `latest`. Thanks again for the PR/suggestions.

**Pull request closed without merging**
