### PR TITLE
Add --update option (#1)

### PR DESCRIPTION
**Pull request by pyrliu**
`--update` flag implements UPSERT support for sync where if row with primary key already exists and conflict occurs, it updates all rows.

We use this instead of `--overwrite` that does `DELETE + INSERT`. DELETE leads to constraint problems and disabling integrity leads easily to other problems.

Co-authored-by: Mikko Harju <mikko@taiste.fi>
Co-authored-by: Pyry Liukas <pyry@taiste.fi>

### CODE REVIEW

**Comment by ankane** [comment]
Hey @pyrliu, thanks for the PR! This is a great idea. Since Postgres 9.4 is now EOL, I think we can switch `--overwrite` to use `INSERT ... ON CONFLICT` without adding an additional option. We should be able to use it for `--preserve` as well with `ON CONFLICT DO NOTHING`. I'm currently working on cleaning up the code, but once that's done, we can get this in and release it as part of pgsync 0.6.0 (aiming for next week).

**Comment by pyrliu** [comment]
Great news 👍

**Comment by ankane** [comment]
Hey @pyrliu, things are currently in a good spot if you want to apply this to the `--overwrite` and `--preserve` options on `master`. I added two new test cases to make sure it handles multiple primary keys correctly (the current pgsync code does not): https://github.com/ankane/pgsync/blob/00b5ff8e8b61af41b4421362118e64b04cc514f3/test/sync_test.rb#L33-L57

Also added a friendly error message for Postgres < 9.5: https://github.com/ankane/pgsync/commit/f95bb5939100b0fff4e739caf7ac251e004e81b8

One minor note: please leave the `.gitignore` change out.

**Comment by pyrliu** [comment]
I tried to clean this up so that instead of separate `--update` `ON CONFLICT` would be used only for `--overwrite` option. Sorry for the messy commit log ✌️ , hopefully this is usable for you.

**Comment by ankane** [comment]
Awesome, thanks @pyrliu! (commits squashed)

**Pull request merged**
